disabled_rules:
  - line_length
  - trailing_whitespace
  - variable_name
  - class_delegate_protocol # This can give false positives if the protocol is inherited.
  - large_tuple
  - nesting
  - todo
  - cyclomatic_complexity
  - function_parameter_count
  - function_body_length
  - file_length
  - unused_closure_parameter
  - type_name
  - shorthand_operator
  - vertical_parameter_alignment

included: # paths to include during linting. `--path` is ignored if present.
  - QOT

excluded:
  - QOT/Generated
