disabled_rules:
    - identifier_name
    - large_tuple
    - todo
    - function_parameter_count
    - type_body_length
    - nesting

file_length:
    warning: 800
    error: 1000

function_body_length:
    warning: 180
    error: 500

line_length:
  warning: 160
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

variable_name:
    max_length:
        warning: 45
        error: 60
    min_length:
        warning: 1

type_name:
    max_length:
        warning: 60
        error: 100
    min_length:
        warning: 1

cyclomatic_complexity:
  warning: 30
  error: 50
  ignores_case_statements: true

included: # paths to include during linting. `--path` is ignored if present.
  - QOT
  - trailing_whitespace

excluded:
  - QOT/Generated
  - QOT/Sources/Theme.swift
  - QOT/Sources/AppText+Extensions.swift
