fastlane_version "2.36.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods(repo_update: true)
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "QOT")
  end

  desc "Deploy to Hockeyapp"
  lane :beta do
    # Install certificates and profiles
    match(type: "adhoc", readonly: true)

    increment_build_number(build_number: ENV["BITRISE_BUILD_NUMBER"])

    # Build
    gym(scheme: "QOT")

    # Release to hockey app
    hockey(api_token: ENV["HOCKEYAPP_API_TOKEN"])
  end

  desc "Deploy to Crashlytics Beta"
  lane :cbeta do
    # Install certificates and profiles
    match(type: "adhoc", readonly: true)

    # Build
    gym(scheme: "QOT")

    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "c5b6a77e0ac832aeb121a8444afaba1522a28469",
      build_secret: "d4ca106b8d4d308cc6c505618f78c345e3e6bd462c0bd7a433abfc3f733a4783"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # Do something
  end
end
